In [1]:
import sys

sys.path.append("../../src")

In [2]:
import numpy as np
import gaussian_overlap
import importlib
import h5py
import pandas as pd
from scipy.linalg import eigh
import matplotlib.pyplot as plt
import copy
import hf_sto_3g
import sto_ng_matrix

from scipy.optimize import minimize

importlib.reload(gaussian_overlap)
importlib.reload(hf_sto_3g)
importlib.reload(sto_ng_matrix)
from gaussian_overlap import *
from sto_ng_matrix import *
from hf_sto_3g import *

In [3]:
df = pd.read_csv("../make_base/sto_3g.csv")
df

exps_1  coefs_1s    exps_2  coefs_2s  coefs_2p
0  0.109987  0.445576  0.074759  0.694673  0.387976
1  0.407154  0.535362  0.229124  0.405616  0.608867
2  2.246014  0.153482  0.979606 -0.100240  0.158557

In [4]:
zeta_1s = 2.69
zeta_2sp = 0.75
n_up = 2
n_dn = 1
scf(zeta_1s, zeta_2sp, df, n_up, n_dn, 3)

(-7.323599382965563,
 array([[-0.99368959, -0.02713542,  0.        ,  0.        ,  0.        ],
        [ 0.25082987, -1.02449905,  0.        ,  0.        ,  0.        ]]),
 array([[-0.9927777 , -0.03083324,  0.        ,  0.        ,  0.        ]]))

In [5]:
Tmat, Vmat, ERImat, Smat = make_matrix(2.69, 0.75, df, 2)

In [6]:
Tmat

array([[ 3.57981892, -0.02097767,  0.        ,  0.        ,  0.        ],
       [-0.02097767,  0.0897154 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.28088307,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.28088307,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.28088307]])

In [7]:
Vmat

array([[-5.32436443, -0.58297544, -0.        , -0.        , -0.        ],
       [-0.58297544, -0.75444854, -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.74815857, -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.74815857, -0.        ],
       [-0.        , -0.        , -0.        , -0.        , -0.74815857]])

In [8]:
ERImat

array([[[[1.68077117, 0.24051762, 0.        , 0.        , 0.        ],
         [0.24051762, 0.37345843, 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.37222419, 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.37222419, 0.        ],
         [0.        , 0.        , 0.        , 0.        , 0.37222419]],

        [[0.24051762, 0.04101792, 0.        , 0.        , 0.        ],
         [0.04101792, 0.07947662, 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.07947851, 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.07947851, 0.        ],
         [0.        , 0.        , 0.        , 0.        , 0.07947851]],

        [[0.        , 0.        , 0.00710277, 0.        , 0.        ],
         [0.        , 0.        , 0.01128587, 0.        , 0.        ],
         [0.00710277, 0.01128587, 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        , 0.        ],
  

In [9]:
def optimize_scf(zetas, df, n_up, n_dn, Z):
    zeta_1s, zeta_2sp = zetas
    energy, _, _ = scf(zeta_1s, zeta_2sp, df, n_up, n_dn, Z)
    return energy


Z = 3
initial_zetas = (2.69, 0.75)
restults = []
result = minimize(optimize_scf, initial_zetas, args=(df, n_up, n_dn, Z))

In [10]:
result

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -7.3291266540236455
        x: [ 2.692e+00  6.522e-01]
      nit: 5
      jac: [-1.907e-06  2.086e-06]
 hess_inv: [[ 5.357e-01 -8.166e-04]
            [-8.166e-04  9.046e-01]]
     nfev: 18
     njev: 6